spring.application.name=api
server.port=8080

spring.datasource.url=${POSTGRES_DB:jdbc:postgresql://localhost:5432/joblens}
spring.datasource.username=${POSTGRES_USER:joblens}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# docker compose auto start (use compose file under api/)
spring.docker.compose.file=api/docker-compose.yml
